class BugDetector:
    """Detects potential usability and UI issues based on the analysis generated by the DOMAnalyser."""

    def __init__(self, analysis: dict):
        self.analysis = analysis

    """
    Detects potential usability and UI issues based on the analysis generated by the DOMAnalyser.
    Returns a list of detected issues."""
    def detect(self):
        bugs = []
        
        """ define variables for easier access to the analysis data """
        forms = self.analysis.get("forms", 0)
        inputs = self.analysis.get("inputs", 0)
        buttons = self.analysis.get("buttons", 0)
        links = self.analysis.get("links", 0)

        # Rule 1
        if forms > 0 and buttons == 0:
            bugs.append(
                "Potential issue: A form was detected without any buttons."
            )

        # Rule 2
        if inputs > 0 and forms == 0:
            bugs.append(
                "Potential issue: Input fields exist outside a form."
            )

        # Rule 3
        if links == 0:
            bugs.append(
                "Potential issue: No navigation links were detected."
            )

        return bugs